name: Deploy static site

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Choose ONE runtime. Bun (fast) or Node+pnpm. Here’s Bun:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        # Astro builds to ./dist by default

      - name: Setup SSH
        run: |
          install -m 600 -D /dev/stdin ~/.ssh/id_ed25519 <<'EOF'
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -az --delete \
            ./dist/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH || '/var/www/mikekey.com' }}/
